import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import Providers from '@/components/Providers';
import { PatientProvider } from '@/context/PatientContext';
import { DoctorProvider } from '@/context/DoctorContext';

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${manrope.className} antialiased`}
      >
        <PatientProvider>
          <DoctorProvider>
            <Providers>
              {children}
            </Providers>
          </DoctorProvider>
        </PatientProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
